### ISSUE TITLE
Scrollback blocked until new message while resizing client

### ISSUE THREAD

**Issue by josuah** [rcr/rirc#18]
Then, I can not scroll while I resized the client.  I use it in either DVTM, tmux, abduco, X11.

If i reduce the size, and then increase it again, I can retrieve all of the text (eventually the whole buffer), so content does not seems to be lost.

To me, this has lower priority than logs, as I could browse logs to check mhat is not on screen.

**Comment by rcr** [comment]
Yeah this has been a known issue for a while...

My first inclination is that this is a bug in how lines are split. I'm already working on replacing the word wrap algorithm since noticing that it actually fails test cases when compiled un-optimized, there's some undefined behaviour, I think the character one before the beginning of the array is being accessed. Once I have a fix for that in place if it's still not working I'll look into the actual draw routine and see if there's an issue there.

**Comment by sshbio** [comment]
I'm impressed that you implemented a `ncurses` alternative that still works well.

I wrote quite a lot of messages, and I hope it is not a problem to you.  I may reduce the level, as holidays are over.

**Comment by sshbio** [comment]
Maybe it is related to your latest commits: as soon as anything is sent (a command, a message...), the scrollback seems to work again.  So it was not really lost, but just blocked.

**Comment by rcr** [comment]
Finally got around to putting in a temp. fix (awaiting for much needed refactoring) for this long overdue bug.

**Comment by josuah** [comment]
Thank you!

Besides, it is nice to see program with terminal UI not using ncurses, I am learning much from draw.c.
